blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.CodeList.as_view(), name='home'),
    # path('<pk:pk>/', views.CodeDetail.as_view(), name='code_detail'),
    path('code/<int:pk>/', views.CodeDetail.as_view(), name='code_detail'),
    path('code/new/', views.code_new, name='code_new'),
    path('code/<int:pk>/edit/', views.code_edit, name='code_edit'),
    path('code/<int:pk>/decode_qr/', views.decode_qr, name='decode_qr'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Code(models.Model):
    title = models.CharField(max_length=200, unique=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
      ordering = ['-created_on']

    def __str__(self):
      return self.title

blog/forms.py
from django import forms
from .models import Code
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

class CodeForm(forms.ModelForm):
  class Meta:
    model = Code
    fields = ('title', 'content',)

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.helper = FormHelper()
    self.helper.layout = Layout(
      Row(
        Column('title', css_class='form-group col-md-6 mb-0'),
        css_class='form-row'
      ),
      Row(
        Column('content', css_class='form-group col-md-6 mb-0'),
        css_class='form-row'
      ),
      Submit('submit', 'Save')
    )

blog/views.py
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from .models import Code
from .forms import CodeForm
from .utils import generate_qr, decode_now

class CodeList(generic.ListView):
  queryset = Code.objects.order_by('-created_on')
  template_name = 'index.html'

class CodeDetail(generic.DetailView):
  model = Code
  template_name = 'code_detail.html'

def code_new(request):
  if request.method == "POST":
    form = CodeForm(request.POST)
    if form.is_valid():
      code = form.save(commit=False)
      code.save()
      generate_qr(code)
      return redirect('code_detail', pk=code.pk)
  else:
    form = CodeForm()
  return render(request, 'code_edit.html', {'form': form})

def code_edit(request, pk):
  code = get_object_or_404(Code, pk=pk)
  if request.method == "POST":
    form = CodeForm(request.POST, instance=code)
    if form.is_valid():
        code = form.save(commit=False)
        code.save()
        generate_qr(code)
        return redirect('code_detail', pk=code.pk)
  else:
    form = CodeForm(instance=code)
  return render(request, 'code_edit.html', {'form': form})

def decode_qr(request, pk):
  code = get_object_or_404(Code, pk=pk)
  result = decode_now(pk)
  return render(request, 'decode_qr.html', {'data': result[0][0], 'pk': pk})

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Read/Write QR Code</title>

    <link
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
      rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"/>
  </head>

  <body>
    <style>
      body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
      }
      .shadow{
        box-shadow: 0 4px 2px -2px rgba(0,0,0,0.1);
       }
      .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
      }
     .masthead {
        background:#3398E1;
        height: auto;
        padding-bottom: 15px;
        box-shadow: 0 16px 48px #E3E7EB;
        padding-top: 10px;
      }
    </style>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Read/Write QR Code</a>
        <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

            <li class="nav-item text-black">
              <a
                class="nav-link text-black font-weight-bold"
                href="#">About</a>
            </li>
            <li class="nav-item text-black">
              <a
                class="nav-link text-black font-weight-bold"
                href="#">Policy</a>
            </li>
            <li class="nav-item text-black">
              <a
                class="nav-link text-black font-weight-bold"
                href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    </nav>
    {% block content %}
    <!-- Content Goes here -->
    {% endblock content %}

    <!-- Footer -->
    <footer class="py-3 bg-grey">
      <p class="m-0 text-dark text-center ">Copyright &copy; Read/Write QR Code</p>
    </footer>
  </body>
</html>

templates/code_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      {% if user.is_authenticated %}
        <a class="text-right" href="{% url 'code_edit' pk=code.pk %}">
          <span class="btn btn-light">Edit</span>
        </a>
      {% endif %}
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ code.author }} | {{ code.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>

  <div class="row">
    <div class="col-md-6">
      <img style="width: 500px; height: 500px;" alt="QR Code" src="/static/images/code-{{code.pk}}.png" />
    </div>

    <div class="col-md-6">
      <a class="float-left btn btn-info" href="{% url 'decode_qr' pk=code.pk %}">Read QR Code</a>
    </div>
  </div>

</div>

{% endblock content %}

templates/code_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container-fluid">
    <h2>Create/Update Code</h2>
    <form method="POST" class="form-group">{% csrf_token %}
      {% crispy form %}
    </form>
  </div>
{% endblock %}

templates/decode_qr.html
Decoded data here:

<h3>{{data}}</h3>


<div><a href="{% url 'code_detail' pk  %}">BACK</a></div>

templates/index.html
{% extends "base.html" %}

{% block content %}
  <style>
    body {
      font-family: "Roboto", sans-serif;
      font-size: 18px;
      background-color: #fdfdfd;
    }
    .head_text{
      color: white;
    }
    .card{
      box-shadow: 0 16px 48px #E3E7EB;
    }
  </style>

  <header class="masthead" >
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class=" col-md-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
            <p class="text-light">Read/Write QR Code &nbsp</p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    {% if user.is_authenticated %}
      <br/>
      <p><a href="{% url 'code_new' %}" class="btn btn-primary">Add Code</a></p>
    {% endif %}

    <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-8 mt-3 left">
        {% for code in code_list %}
          <div class="card mb-4" >
            <div class="card-body">
              <h2 class="card-title">{{ code.title }}</h2>
              <p class="card-text text-muted h6">{{ code.Author }} | {{ code.created_on}} </p>
              <p class="card-text">{{code.content|slice:":200" }}</p>
              <a href="{% url 'code_detail' code.pk  %}" class="btn btn-secondary">View &rarr;</a>
            </div>
          </div>
        {% endfor %}
      </div>
      {% block sidebar %}
      {% include 'sidebar.html' %}
      {% endblock sidebar %}
    </div>
  </div>
{% endblock %}

templates/sidebar.html
{% block sidebar %}

<style>
  .card{
    box-shadow: 0 16px 48px #E3E7EB;
  }
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
  <div class="card my-4">
    <h5 class="card-header">About Us</h5>
    <div class="card-body">
      <p class="card-text">This blog is an implementation of reading and writing QR Code with given information using python libraries.</p>
      <a href="#" class="btn btn-danger">Know more!</a>
    </div>
  </div>
</div>

{% endblock sidebar %}